CREATE USER INVENTORY2 IDENTIFIED BY INVENTORY2;

GRANT CONNECT,RESOURCE,DBA TO INVENTORY2;

GRANT CREATE SESSION,GRANT ANY PRIVILEGE TO INVENTORY2;

GRANT UNLIMITED TABLESPACE TO INVENTORY2;

